#!/usr/bin/env node
/**
 * CC Orchestrator Setup Script
 * API 키 입력 및 환경 설정
 */

import * as readline from 'readline';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      resolve(answer.trim());
    });
  });
}

function questionHidden(prompt) {
  return new Promise((resolve) => {
    process.stdout.write(prompt);

    const stdin = process.stdin;
    const wasRaw = stdin.isRaw;

    stdin.setRawMode(true);
    stdin.resume();
    stdin.setEncoding('utf8');

    let input = '';

    const onData = (char) => {
      if (char === '\n' || char === '\r') {
        stdin.setRawMode(wasRaw);
        stdin.removeListener('data', onData);
        process.stdout.write('\n');
        resolve(input);
      } else if (char === '\u0003') {
        // Ctrl+C
        process.exit();
      } else if (char === '\u007F' || char === '\b') {
        // Backspace
        if (input.length > 0) {
          input = input.slice(0, -1);
          process.stdout.write('\b \b');
        }
      } else {
        input += char;
        process.stdout.write('*');
      }
    };

    stdin.on('data', onData);
  });
}

async function main() {
  console.log('\n╔════════════════════════════════════════════════════════════╗');
  console.log('║           CC Orchestrator - Claude Code Multi-Model Orchestrator       ║');
  console.log('║                        Setup Wizard                         ║');
  console.log('╚════════════════════════════════════════════════════════════╝\n');

  console.log('이 스크립트는 CC Orchestrator MCP 서버 설정을 도와줍니다.\n');
  console.log('필요한 API 키:');
  console.log('  - OpenAI API Key (GPT 모델용)');
  console.log('  - Google API Key (Gemini 모델용)');
  console.log('  - Anthropic API Key (Claude 모델용)\n');
  console.log('참고: 일부 API 키가 없어도 해당 모델을 사용하지 않으면 됩니다.\n');
  console.log('─'.repeat(60) + '\n');

  // API 키 입력 받기
  const openaiKey = await question('OpenAI API Key (Enter to skip): ');
  const googleKey = await question('Google API Key (Enter to skip): ');
  const anthropicKey = await question('Anthropic API Key (Enter to skip): ');

  console.log('\n─'.repeat(60));

  // 입력 확인
  console.log('\n입력된 API 키:');
  console.log(`  OpenAI:    ${openaiKey ? '✓ 설정됨' : '✗ 건너뜀'}`);
  console.log(`  Google:    ${googleKey ? '✓ 설정됨' : '✗ 건너뜀'}`);
  console.log(`  Anthropic: ${anthropicKey ? '✓ 설정됨' : '✗ 건너뜀'}`);

  if (!openaiKey && !googleKey && !anthropicKey) {
    console.log('\n⚠️  경고: API 키가 하나도 설정되지 않았습니다.');
    console.log('   에이전트 기능을 사용하려면 최소 하나의 API 키가 필요합니다.\n');
  }

  const confirm = await question('\n이 설정으로 계속하시겠습니까? (Y/n): ');

  if (confirm.toLowerCase() === 'n') {
    console.log('\n설정이 취소되었습니다.\n');
    rl.close();
    process.exit(0);
  }

  // .env 파일 생성
  console.log('\n📝 .env 파일 생성 중...');

  const envContent = `# CC Orchestrator API Keys
# Generated by setup script

# OpenAI API Key (GPT 모델용 - oracle 역할)
OPENAI_API_KEY=${openaiKey}

# Google API Key (Gemini 모델용 - frontend-engineer, document-writer, multimodal-analyzer 역할)
GOOGLE_API_KEY=${googleKey}

# Anthropic API Key (Claude 모델용 - librarian 역할)
ANTHROPIC_API_KEY=${anthropicKey}

# Server Configuration
LOG_LEVEL=info
NODE_ENV=production
CC Orchestrator_MAX_PARALLEL_AGENTS=5
CC Orchestrator_TIMEOUT_SECONDS=300
`;

  const envPath = path.join(rootDir, '.env');
  fs.writeFileSync(envPath, envContent);
  console.log('   ✓ .env 파일이 생성되었습니다.');

  // npm install
  console.log('\n📦 의존성 설치 중...');
  try {
    execSync('npm install', { cwd: rootDir, stdio: 'inherit' });
    console.log('   ✓ 의존성 설치 완료');
  } catch (error) {
    console.error('   ✗ 의존성 설치 실패');
    rl.close();
    process.exit(1);
  }

  // npm run build
  console.log('\n🔨 프로젝트 빌드 중...');
  try {
    execSync('npm run build', { cwd: rootDir, stdio: 'inherit' });
    console.log('   ✓ 빌드 완료');
  } catch (error) {
    console.error('   ✗ 빌드 실패');
    rl.close();
    process.exit(1);
  }

  // Claude Code 설정 안내
  console.log('\n' + '═'.repeat(60));
  console.log('\n✅ CC Orchestrator 설치가 완료되었습니다!\n');
  console.log('다음 단계: Claude Code에 MCP 서버를 등록하세요.\n');

  console.log('📋 Claude Desktop 설정 파일 위치:');
  console.log('   Windows: %APPDATA%\\Claude\\claude_desktop_config.json');
  console.log('   macOS:   ~/Library/Application Support/Claude/claude_desktop_config.json\n');

  console.log('📝 다음 내용을 설정 파일에 추가하세요:\n');

  const configExample = {
    mcpServers: {
      cc-orchestrator: {
        command: 'node',
        args: [path.join(rootDir, 'dist', 'index.js').replace(/\\/g, '\\\\')],
        env: {
          OPENAI_API_KEY: openaiKey || 'your-openai-key',
          GOOGLE_API_KEY: googleKey || 'your-google-key',
          ANTHROPIC_API_KEY: anthropicKey || 'your-anthropic-key',
        },
      },
    },
  };

  console.log(JSON.stringify(configExample, null, 2));

  console.log('\n⚠️  설정 후 Claude Code를 재시작하세요.');
  console.log('\n' + '═'.repeat(60) + '\n');

  rl.close();
}

main().catch((error) => {
  console.error('오류 발생:', error);
  rl.close();
  process.exit(1);
});
